#	This file is part of Edge Registry.
#
#    Edge Registry is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Edge Registry is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Edge Registry.  If not, see https://www.gnu.org/licenses/.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-hosts
  namespace: edgestorage
  labels:
    k8s-app: registry-hosts
spec:
  selector:
    matchLabels:
      name: registry-hosts
  template:
    metadata:
      labels:
        name: registry-hosts
    spec:
      containers:
      - name: registry-hosts
        image: busybox
        command: ['sh']
        args: ['-c','grep -qF dkms.edge.registry  /hostetc/hosts || echo "{{ACES_REGISTRY_ENDPOINT}} dkms.edge.registry" >> /hostetc/hosts && exec tail -f /dev/null' ]
        volumeMounts:
        - name: etc-host
          mountPath: /hostetc
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etc-host
        hostPath:
          path: /etc