#	This file is part of Edge Storage Enabler.
#
#    Edge Storage Enabler is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Edge Storage Enabler is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Edge Storage Enabler.  If not, see https://www.gnu.org/licenses/.

apiVersion: v1
kind: Namespace
metadata:
  name: edgestorage
  labels:
    app: edgestorage
---
apiVersion: v1
data:
    access-key: {{edgeKey}}
    secret-key: {{edgeSecret}}
kind: Secret
metadata:
  name: edge-keys
  namespace: edgestorage
  labels:
    app: edgestorage
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJWUHNvbWFrIiwicGFzc3dvcmQiOiJnaHBfOFZtc0NjWXlYZUdsV2kxa3B3eEEwOWFqa1MwRExVMGhCV2NMIiwiYXV0aCI6IlZsQnpiMjFoYXpwbmFIQmZPRlp0YzBOaldYbFlaVWRzVjJreGEzQjNlRUV3T1dGcWExTXdSRXhWTUdoQ1YyTk0ifX19
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: edge-storage-token
  namespace: edgestorage
  labels:
    app: edgestorage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-serviceaccount
  namespace: edgestorage
  labels:
    app: edgestorage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edge-role
  namespace: edgestorage
  labels:
    app: edgestorage
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - 'edge-keys'
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edge-role-binding
  namespace: edgestorage
  labels:
    app: edgestorage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edge-role
subjects:
- kind: ServiceAccount
  name: edge-serviceaccount
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: edgestorage
  name: edge-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: edge-pv-class
  local:
    path: {{dataPath}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: edge-storage-worker
          operator: In
          values:
          - "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: edge-claim
  namespace: edgestorage
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: edge-pv-class
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: edgestorage
  name: edgestorage
spec:
  serviceName: edgestorage
  replicas: {{edgeServers}}
  selector:
    matchLabels:
      app: edgestorage
  template:
    metadata:
      labels:
        app: edgestorage
    spec:
      serviceAccountName: edge-serviceaccount
      nodeSelector:
        edge-storage-worker: "true"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: edge-claim
      containers:
      - name: edgestorage
        #image: dimianstudio/minio-arm
        image: ghcr.io/dkmslab/edge-storage-component
        imagePullPolicy: Always
        securityContext:
            privileged: true
        args:
        - server
        - /data
        - --console-address
        - :9001
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: edge-keys
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: edge-keys
              key: secret-key
        ports:
        - containerPort: 9000
          hostPort: 9010
        - containerPort: 9001
          hostPort: 9011
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: data
          mountPath: /data
      imagePullSecrets:
        - name: edge-storage-token
---
apiVersion: v1
kind: Service
metadata:
  name: edgestorage
  namespace: edgestorage
  labels:
    app: edgestorage
spec:
  clusterIP: None
  selector:
    app: edgestorage
  ports:
  - port: 9011
    name: edgestorage
---
apiVersion: v1
kind: Service
metadata:
  name: edge-service
  namespace: edgestorage
  labels:
    app: edgestorage
spec:
  type: LoadBalancer
  selector:
    app: edgestorage
  ports:
  - port: 9012
    targetPort: 9011
    protocol: TCP