#	This file is part of ACCORDION Monitoring Aggregator.
#
#    ACCORDION Monitoring Aggregator is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ACCORDION Monitoring Aggregator is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ACCORDION Monitoring Aggregator.  If not, see https://www.gnu.org/licenses/.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aces-registry
  name: aces-registry
  namespace: aces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aces-registry
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aces-registry
    spec:
      hostNetwork: true
      containers:
        - env:
            # - name: REGISTRY_AUTH
              # value: "htpasswd"
            # - name: REGISTRY_AUTH_HTPASSWD_REALM
              # value: "Registry Realm"
            # - name: REGISTRY_AUTH_HTPASSWD_PATH
              # value: "/auth/htpasswd"
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:5045"
            - name: REGISTRY_HTTP_HOST
              value: "https://accordion.aces.registry:5045"
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/certs/tls.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/certs/tls.key"
            - name: REGISTRY_STORAGE
              value: s3
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: aces-keys
                  key: access-key
            - name: REGISTRY_STORAGE_S3_BUCKET
              value: "registry-aces"
            - name: REGISTRY_STORAGE_S3_REGION
              value: us-east-1
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: aces-keys
                  key: secret-key
            - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
              value: {{ACES_ENDPOINT}}
          image: registry:2
          name: registry
          ports:
            - containerPort: 5045
          volumeMounts:
            - name: certs-vol
              mountPath: "/certs"
              readOnly: true
            - name: auth-vol
              mountPath: "/auth"
              readOnly: true
      volumes:
        - name: certs-vol
          secret:
            secretName: aces-registry-secret
        - name: auth-vol
          secret:
            secretName: aces-registry-auth