#	This file is part of Edge Registry Syncer.
#
#    Edge Registry Syncer is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Edge Registry Syncer is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Edge Registry Syncer.  If not, see https://www.gnu.org/licenses/.

apiVersion: v1
kind: Namespace
metadata:
  name: edge-sync
  labels:
    name: edge-sync
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJWUHNvbWFrIiwicGFzc3dvcmQiOiJnaHBfOFZtc0NjWXlYZUdsV2kxa3B3eEEwOWFqa1MwRExVMGhCV2NMIiwiYXV0aCI6IlZsQnpiMjFoYXpwbmFIQmZPRlp0YzBOaldYbFlaVWRzVjJreGEzQjNlRUV3T1dGcWExTXdSRXhWTUdoQ1YyTk0ifX19
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: edge-sync-token
  namespace: edge-sync
  labels:
    app.kubernetes.io/name: edge-sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-sync
  namespace: edge-sync
  labels:
    app.kubernetes.io/name: edge-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: edge-sync
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edge-sync
    spec:
      hostNetwork: true
      containers:
        - name: edge-sync-daemon
          image: ghcr.io/dkmslab/edge-registry-sync-daemon
          imagePullPolicy: Always
          command: ["python"]
          args: ["/pythoncode/edge_repo_sync_daemon.py"]
          env:
          - name: REPOSYNCPORT
            value: "2022"
          - name: REPOURL
            value: "dkms.edge.registry:5045"
          - name: KUBECONFIG
            value: "/k3sconf/k3s.yaml"
          - name: KAFKA_ADDRESS
            value: "195.148.125.135:9092"
          volumeMounts:
          - name: auths-host
            mountPath: /repoauths
          - name: kubeconf-host
            mountPath: /k3sconf
          - name: yamltemplates
            mountPath: /yamltemplates
        - name: edge-kafka-daemon
          image: ghcr.io/dkmslab/edge-registry-sync-daemon
          imagePullPolicy: Always
          command: ["python"]
          args: ["/pythoncode/edge_kafka_daemon.py"]
      imagePullSecrets:
        - name: edge-sync-token
      volumes:
      - name: auths-host
        hostPath:
          path: {{EDGE_SYNC_PATH}}/repoauths
      - name: kubeconf-host
        hostPath:
          path: /etc/rancher/k3s
      - name: yamltemplates
        hostPath:
          path: {{EDGE_SYNC_PATH}}/yamltemplates